version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: web/nginx/Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    networks:
      - app-network
  fpm:
    build:
      context: .
      dockerfile: web/fpm/Dockerfile
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    links:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - 3309:3309
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
    networks:
      - app-network
networks:
  app-network:
    driver: bridge