<?php


namespace frontend\controllers;

use common\repositories\MessageRepository;
use yii\data\ActiveDataProvider;

class InvalidMessageController extends AdminController
{
    /**
     * @var MessageRepository
     */
    private $messages;

    /**
     *
     */
    public function init()
    {
        $this->messages = new MessageRepository();

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => $this->messages->getInvalidMessages(),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }
}